config/routes.rb
Exam::Application.routes.draw do
  resources :clinics do
    resources :doctors
  end

  root :to =>"home#index"

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  attr_accessible :id, :name
  validates :name, :presence => true
  has_many :doctors, :dependent => :destroy
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :clinic
  attr_accessible :id, :name
  validates :name, :presence => true,
                  :uniqueness => true
  default_scope :order => 'doctors.created_at DESC'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clinics }
    end
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
    @clinic = Clinic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clinic }
    end
  end

  # GET /clinics/new
  # GET /clinics/new.json
  def new
    @clinic = Clinic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clinic }
    end
  end

  # GET /clinics/1/edit
  def edit
    @clinic = Clinic.find(params[:id])
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(params[:clinic])

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clinic was successfully created.' }
        format.json { render json: @clinic, status: :created, location: @clinic }
      else
        format.html { render action: "new" }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clinics/1
  # PUT /clinics/1.json
  def update
    @clinic = Clinic.find(params[:id])

    respond_to do |format|
      if @clinic.update_attributes(params[:clinic])
        format.html { redirect_to @clinic, notice: 'Clinic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic = Clinic.find(params[:id])
    @clinic.destroy

    respond_to do |format|
      format.html { redirect_to clinics_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def create
    @clinic = Clinic.find(params[:clinic_id])
    @doctor = @clinic.doctors.create(params[:doctor])
    redirect_to clinic_path(@clinic), :notice => 'Create Successful'
  end

  def destroy
    @clinic = Clinic.find(params[:clinic_id])
    @doctor = @clinic.doctors.find(params[:id])
    @doctor.destroy
    redirect_to clinic_path(@clinic)
  end
  
  def edit
    @clinic = Clinic.find(params[:clinic_id])
    @doctor = @clinic.doctors.find(params[:id])
  end

  def update
    @clinic = Clinic.find(params[:clinic_id])
    @doctor = @clinic.doctors.find(params[:id])
    respond_to do |format|
    	if @doctor.update_attributes(params[:doctor])
	   format.html {redirect_to(@clinic, :notice => 'Update Complete')}
        else 
           format.html {redirect_to(@clinic, :notice => 'Update Failed')}
    	end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clinics/_form.html.erb
<%= form_for(@clinic) do |f| %>
  <% if @clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinic.errors.count, "error") %> prohibited this clinic from being saved:</h2>

      <ul>
      <% @clinic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!--  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>-->
  <div class="field">
     <%= f.label :name, class: "control-lable"%>
     <%= f.text_field :name%>
  </div>
  <div class ="field">
     <%=f.submit%>
  </div>
<% end %>

app/views/clinics/edit.html.erb
<div class="navbar navbar-fixed-center">
  <div class="navbar-inner">
    <div class="container">
    <div class = "masthead">
        <h1>Edit This Clinic</h1>
    </div>

    <%= render 'form' %>
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Show", @clinic, class: "brand"%>
      <%= link_to "Back", clinics_path, class: "brand" %>
      <div class="nav-collapse">
        <ul class="nav">
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/clinics/index.html.erb
<div class="navbar navbar-fixed-center">
  <div class="navbar-inner">
    <div class="container">
<hr />
<div class = "masthead">
	<h1>Listing Clinics</h1>
</div>

<table class = "table table-striped table-bordered">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clinics.each do |clinic| %>
  <tr>
    <td><%= clinic.id %></td>
    <td><%= clinic.name %></td>
    <td><%= link_to 'Show', clinic %></td>
    <td><%= link_to 'Edit', edit_clinic_path(clinic) %></td>
    <td><%= link_to 'Destroy', clinic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<hr />
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      <%= link_to 'New Clinic', new_clinic_path, class: "brand" %>

      </a>

<div class="nav-collapse">
        <ul class="nav">
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/clinics/new.html.erb
<div class="navbar navbar-fixed-center">
  <div class="navbar-inner">
    <div class="container">
    <div class = "masthead">
        <h1>Create A New Clinic</h1>
    </div>

    <%= render 'form' %>
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Back", clinics_path, class: "brand" %>
      <div class="nav-collapse">
        <ul class="nav">
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/clinics/show.html.erb
<div class="navbar navbar-fixed-center">
  <div class="navbar-inner">
    <div class="container">
<div class = "masthead">
        <h1>Clinic <%=@clinic.name%></h1>
</div>


<table class = "table table-striped table-bordered">
<tr>
   <th>ID</th>
   <th>Name</th>
   <th></th>
   <th></th>
</tr>
<%= render @clinic.doctors %>
</table>

<hr />
<div class = "masthead">
        <h3>Add a New Doctor for This Clinic</h3>
</div>

<%= render "doctors/form"%>
<br />
<hr />
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      <%= link_to 'Edit', edit_clinic_path(@clinic), class: "brand" %>
      <%= link_to 'Back', @clinic, class: "brand" %>
      </a>

<div class="nav-collapse">
        <ul class="nav">
        </ul>
      </div>
    </div>
  </div>
</div>
           

app/views/doctors/_doctor.html.erb
<tr>
   <td><%= doctor.id%></td>
   <td><%= doctor.name %></td>
   <td><%= link_to 'Edit', edit_clinic_doctor_path(doctor.clinic, doctor)%></td>
   <td><%= link_to 'Delete', [doctor.clinic, doctor], :confirm => 'Are you sure', :method => :delete%></td>
</tr>

app/views/doctors/_form.html.erb
<%= form_for([@clinic, @clinic.doctors.build]) do |f| %>
   <% if @clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinic.errors.count, "error") %> prohibited this clinic from being saved:</h2>

      <ul>
      <% @clinic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
     <%= f.label :name, class: "control-lable"%>
     <%= f.text_field :name%>
  </div>
  <div class ="field">
     <%=f.submit%>
  </div>

<%end%>

app/views/doctors/edit.html.erb
<div class="navbar navbar-fixed-center">
  <div class="navbar-inner">
    <div class="container">
    <div class = "masthead">
        <h1>Edit This Doctor Profile</h1>
    </div>

<%= form_for ([@clinic, @doctor]) do |f|%>
  <div class = "field">
     <%= f.label :name %>
     <%= f.text_field :name%>
  </div>
  <div class = "actions">
     <%= f.submit%>
  </div>
<%end%>
 <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Show", @clinic, class: "brand"%>
      <%= link_to "Back", clinics_path, class: "brand" %>
      <div class="nav-collapse">
        <ul class="nav">
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="navbar navbar-fixed-center">
  <div class="navbar-inner">
    <div class="container">
    <div class="masthead">
        <h3 class="muted">Clinic#Doctor</h3>
    </div>
    <hr/>
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
<!--      <%= link_to "Clinic-List", clinics_path, class: "brand" %>-->
      <a class="btn btn-large btn-success" href="<%=clinics_path%>"><i class="icon-lock"></i>             Clinic-List             </a>
      <div class="nav-collapse">
        <ul class="nav">
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<%= link_to "Clinic", clinics_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exam</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>